[package]
name = "dispatch_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-cors = "0.7"
mongodb = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bcrypt = "0.15"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
actix-ws = "0.3"
tokio    = { version = "1", features = ["full"] }